# Updates the Readme.
name: Readme Update

on:
  # Runs on Push to main
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "readme"
  readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the CreateReadme.py to update readme
        run: |
          python CreateReadme.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v6
        with:
          author_name: nickdehart
          author_email: nickdehart@gmail.com
          message: "Updated Readme"
          add: "."
